<meta charset="utf-8">
<style>
    <?= $css ?>
</style>

<?php
    $pages = ($hasBackPage) ? $members->chunk(4) : $members->chunk(8);
?>

<?php foreach ( $pages as $members ) : ?>
    <div class="page">
        <?php foreach ( $members as $member ) : ?>

            <div class="card horizontal-card <?= ( ! $hasBackPage )  ? 'no-back-page': '' ?>">
                <div class="front-page">
                    <div class="images">
                        <img src="<?= $company->logo ?>" alt="" class="logo">

                        <?php $alt = ( $member->photo !== null ) ? $member->name : '' ?>
                        <img src="<?= $member->photo ?>" alt="<?= $alt ?>" class="picture">

                    </div>

                    <div class="user-info">
                        <span class="user-name"><?= $member->shortName ?></span>
                        <hr>
                        <div class="card-info">
                            <span class="left">Emitido em: <?= date('d/m/Y') ?></span>
                            <span class="right"><?= $member->regNumber ?></span>
                        </div>
                    </div>
                </div>

                <?php if( $hasBackPage ) :?>
                    <div class="back-page">
                        <div class="card-info">
                        <span class="left">
                            <?= str_pad(date('Ymd'), 11, 0, STR_PAD_LEFT)?>
                        </span>
                            <span class="right card-type text-upper">
                            <?= $company->type ?>
                        </span>
                        </div>
                        <div class="user-info">
                            <?php $i = 0; ?>
                            <?php foreach ( $member->userInfo as $key => $info ) : ?>
                            <span class="<?= ($i % 2 === 0) ? 'left' : 'right' ?>">
                                <b><?= $key ?>: </b> <?= $info?>

                                <?php $i++?>
                                </span><?= ($i % 2 === 0 ) ? '<br>' : '' ?>
                            <?php endforeach; ?>
                        </div>
                        <div class="company-info">
                            <?php foreach ( $company->companyInfo as $c ) : ?>
                                <?= $c ?><br>
                            <?php endforeach; ?>
                        </div>
                        <div class="general-info">
                            <?php foreach ($company->cardInfo as $c) : ?>
                                * <?= $c ?><br>
                            <?php endforeach; ?>
                        </div>
                        <div class="codebar">
                            <div class="codebar-wrapper">
                                <img src="<?= $member->barCode ?>">
                            </div>
                        </div>
                    </div>
                <?php endif;?>
            </div>
        <?php endforeach;?>
    </div>
<?php endforeach;?>
