<meta charset="utf-8">
<style>
    <?= $css ?>
</style>

<?php
    $pages = ($hasBackPage) ? $members->chunk(2) : $members->chunk(6);
?>

<?php foreach ( $pages as $members ) : ?>

    <div class="page">
        <?php foreach ( $members as $member ) : ?>

            <div class="card vertical-card <?= ( ! $hasBackPage )  ? 'no-back-page': '' ?>">
                <div class="front-page">
                    <div class="logo">
                        <img src="<?= $company->logo ?>" alt="">
                    </div>
                    <div class="picture">
                        <?php $alt = ( $member->photo !== null ) ? $member->name : '' ?>
                        <img src="<?= $member->photo ?>" alt="<?= $alt ?>">
                    </div>

                    <div class="user-info">
                        <div class="user-info-wrapper">
                            <span class="user-name"><?= $member->shortName ?></span>
                            <hr>
                            <div class="card-info">
                                <span><?= $member->job ?></span>
                            </div>
                        </div>
                    </div>
                </div>

                <?php if( $hasBackPage ) : ?>
                    <div class="back-page">
                        <div class="card-info text-upper">
                            <span><?= $company->type ?></span>
                            <span><?= str_pad(date('Ymd'), 11, 0, STR_PAD_LEFT)?></span>
                        </div>
                        <div class="user-info">
                            <?php foreach ( $member->userInfo as $key => $info ) : ?>
                                <span>
                                    <b><?= $key ?>: </b> <?= $info?>
                                </span><br>
                            <?php endforeach; ?>
                        </div>
                        <div class="company-info">
                            <?php foreach ( $company->companyInfo as $c ) : ?>
                                <?= $c?><br>
                            <?php endforeach; ?>
                        </div>
                        <div class="general-info">
                            <?php foreach ( $company->cardInfo as $c ) : ?>
                                * <?= $c ?><br>
                            <?php endforeach; ?>
                        </div>
                        <div class="codebar">
                            <div class="codebar-wrapper">
                                <img src="<?= $member->barCode ?>">
                            </div>
                        </div>
                    </div>
                <?php endif;?>
            </div>
        <?php endforeach;?>

    </div>

<?php endforeach; ?>
