language: php

php:
    - 8.1

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --dev

script:
    - mkdir -p build/logs
    - vendor/bin/pest
    - vendor/bin/pint -dry-run
