language: php

php:
    - 7.0.8
    - 7.1

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --dev
    - sudo apt-get install wkhtmltopdf
    - whereis wkhtmltopdf

script:
    - mkdir -p build/logs
    - vendor/bin/phpunit