language: php

php:
    - 8.1

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --dev

script:
    - mkdir -p build/logs
    - vendor/bin/pint --test
    - vendor/bin/phpcs --standard=phpcs.xml
    - vendor/bin/phpmd src text ./phpmd.xml
    - vendor/bin/pest
